import gleam/string
import simplifile
import tom

pub fn generate_version_file_content(toml_string: String) -> String {
  let version = case tom.parse(toml_string) {
    Ok(toml) -> {
      case tom.get_string(toml, ["version"]) {
        Ok(v) -> v
        Error(_) -> "dev"
      }
    }
    Error(_) -> "dev"
  }

  [
    "// This file was generated by scopa/dev/scripts/generate_version",
    "// You typically do not need to edit this file",
    "pub const version = \"" <> version <> "\"",
  ]
  |> string.join("\n")
}

const core = "../core/"

pub fn main() {
  let assert Ok(_) = simplifile.create_directory_all(core <> "src/generated/")

  let assert Ok(toml) = simplifile.read(from: core <> "gleam.toml")
  let contents = generate_version_file_content(toml)
  let target = core <> "src/generated/version.gleam"
  let assert Ok(_) = simplifile.write(to: target, contents:)
}
