[tools]
gleam = "1.16"
erlang = "28"
rebar = "3.27"

[tasks.dev-build]
description = "Build dev project"
dir = "./dev"
run = "gleam build"

[tasks.core-build]
description = "Build core project"
depends = ["dev-run"]
dir = "./core"
run = "gleam build"

[tasks.build]
description = "Build all projects in dependency order"
depends = ["core-build"]

[tasks.dev-test]
description = "Test dev project"
dir = "./dev"
run = "gleam test"

[tasks.core-test]
description = "Test core project"
depends = ["dev-run"]
dir = "./core"
run = "gleam test"

[tasks.test]
depends = ["dev-test", "core-test"]

[tasks.dev-run]
description = "Run dev project"
dir = "./dev"
run = """
gleam run --module scripts/generate_version
"""

[tasks.core-run]
description = "Run core project"
depends = ["dev-build"]
dir = "./core"
run = "gleam run --module lustre/dev start"

[tasks.default]
description = "Run core project"
depends = ["core-run"]

[tasks.dev-clean]
description = "Clean dev project"
dir = "./dev"
run = "gleam clean"

[tasks.core-clean]
description = "Clean core project"
dir = "./core"
run = "gleam clean"

[tasks.clean]
depends = ["dev-clean", "core-clean"]
