name = "mf2"
version = "0.0.0"
description = "Gleam MessageFormat 2 implementation"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
mf2_parser = { path = "../mf2_parser" }

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
dev_test = { path = "../dev_test" }
