import gleam/io
import gleam/string
import simplifile
import tom

fn generate_version_file_content(toml_string: String) -> #(String, String) {
  let version = case tom.parse(toml_string) {
    Ok(toml) -> {
      case tom.get_string(toml, ["version"]) {
        Ok(v) -> v
        Error(_) -> "dev"
      }
    }
    Error(_) -> "dev"
  }

  let source =
    [
      "// This file was generated by tolke/build_pipeline/scripts/generate_version",
      "// You typically do not need to edit this file",
      "pub const version = \"" <> version <> "\"",
    ]
    |> string.join("\n")

  #(source, version)
}

const dev_tools = "../dev_tools/"

const target_folder = dev_tools <> "src/internal/generated/"

pub fn generate_version() -> String {
  let assert Ok(_) = simplifile.create_directory_all(target_folder)

  let gleam_toml = dev_tools <> "gleam.toml"
  let assert Ok(toml) = simplifile.read(from: gleam_toml)

  let #(contents, version) = generate_version_file_content(toml)

  let target = target_folder <> "version.gleam"
  let assert Ok(_) = simplifile.write(to: target, contents:)

  io.println("generated: " <> target)

  version
}
