import gleam/http/request
import gleam/httpc.{type HttpError}
import gleam/io
import gleam/list
import gleam/result
import gleam/string
import gleam/uri
import simplifile

const target_folder = "../core/src/internal/generated/"

const target_source = target_folder <> "iana_definitions.gleam"

pub fn generate_valid_iana_subtags() {
  let quoted = fn(value) { "\"" <> value <> "\"" }

  case simplifile.is_file(target_source) {
    Ok(True) -> io.println("reused: " <> target_source <> " used")
    Ok(False) | Error(_) -> {
      let assert Ok(registry) = fetch_registry()
      let registry = parse_registry(registry)

      let languages =
        registry.languages
        |> list.map(fn(l) { quoted(l.code) })
        |> list.sort(fn(a, b) { string.compare(a, b) })

      let scripts =
        registry.scripts
        |> list.map(fn(s) { quoted(s.code) })
        |> list.sort(fn(a, b) { string.compare(a, b) })

      let regions =
        registry.regions
        |> list.map(fn(r) { quoted(r.code) })
        |> list.sort(fn(a, b) { string.compare(a, b) })

      let contents = "
// This file was generated by tolke/dev/scripts/generate_valid_iana_subtags
// You typically do not need to edit this file

import gleam/list

const valid_languages = [" <> languages |> string.join(", ") <> "]
pub fn is_valid_language(value: String) { valid_languages |> list.contains(value) }

const valid_scripts = [" <> scripts |> string.join(", ") <> "]
pub fn is_valid_script(value: String) { valid_scripts |> list.contains(value) }

const valid_regions = [" <> regions |> string.join(", ") <> "]
pub fn is_valid_region(value: String) { valid_regions |> list.contains(value) }
"
      let assert Ok(_) = simplifile.create_directory_all(target_folder)
      let assert Ok(_) = simplifile.write(to: target_source, contents:)

      io.println("generated: " <> target_source)
    }
  }
}

type Language {
  Language(code: String, description: String)
}

type Script {
  Script(code: String, description: String)
}

type Region {
  Region(code: String, description: String)
}

type Registry {
  Registry(
    languages: List(Language),
    scripts: List(Script),
    regions: List(Region),
  )
}

fn fetch_registry() -> Result(String, HttpError) {
  let assert Ok(uri) =
    uri.parse(
      "https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry",
    )
  let assert Ok(req) = request.from_uri(uri)

  httpc.send(req)
  |> result.map(fn(resp) { resp.body })
}

fn parse_registry(raw: String) -> Registry {
  raw
  |> split_records
  |> list.fold(Registry([], [], []), fn(acc, record) {
    case parse_record(record) {
      Ok(item) ->
        case item {
          LanguageItem(lang) ->
            Registry([lang, ..acc.languages], acc.scripts, acc.regions)

          ScriptItem(script) ->
            Registry(acc.languages, [script, ..acc.scripts], acc.regions)

          RegionItem(region) ->
            Registry(acc.languages, acc.scripts, [region, ..acc.regions])
        }

      Error(_) -> acc
    }
  })
}

type Item {
  LanguageItem(Language)
  ScriptItem(Script)
  RegionItem(Region)
}

fn split_records(raw: String) -> List(String) {
  raw
  |> string.split("%%")
  |> list.map(string.trim)
  |> list.filter(fn(s) { string.length(s) > 0 })
}

fn parse_record(record: String) -> Result(Item, Nil) {
  let lines =
    record
    |> string.split("\n")
    |> list.map(string.trim)

  let typ = find_field(lines, "Type")
  let subtag = find_field(lines, "Subtag")
  let desc = find_field(lines, "Description")

  case typ, subtag, desc {
    Ok("language"), Ok(code), Ok(d) -> Ok(LanguageItem(Language(code, d)))
    Ok("script"), Ok(code), Ok(d) -> Ok(ScriptItem(Script(code, d)))
    Ok("region"), Ok(code), Ok(d) -> Ok(RegionItem(Region(code, d)))
    _, _, _ -> Error(Nil)
  }
}

fn find_field(lines: List(String), key: String) -> Result(String, Nil) {
  lines
  |> list.find_map(fn(line) {
    case string.split_once(line, ":") {
      Ok(result) -> {
        let #(k, v) = result
        case string.trim(k) == key {
          True -> Ok(string.trim(v))
          False -> Error(Nil)
        }
      }

      _ -> Error(Nil)
    }
  })
}
