name = "tolke_dev_tools"
version = "0.0.0"

description = """
tolke_dev_tools turns MessageFormat 2 files into type-safe Gleam code.
It compiles messages into convenient functions, validates consistency across
locales, and supports both runtime and compile-time locale bundles.
"""

licences = ["BSD-3-Clause"]
repository = { type = "github", user = "nigeleke", repo = "tolke" }
# links = [{ title = "Website", href = "" }]

internal_modules = ["dev_tools/internal"]

[dependencies]
filepath = ">= 1.1.2 and < 2.0.0"
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
parsley = { path = "../parsley" }
simplifile = ">= 2.4.0 and < 3.0.0"
tom = ">= 2.1.0 and < 3.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
